name: eletronic_schedule
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_local_notifications: ^9.5.3+1
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  mask_text_input_formatter: ^2.3.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  sqflite: ^2.0.2
  path: ^1.8.0
  image_picker: ^0.8.4+5
  shared_preferences: ^2.0.12

flutter: 
  uses-material-design: true

